#!/usr/bin/env bash
# init.sh — Initialize .agent/ workspace
# Usage: curl -fsSL https://raw.githubusercontent.com/humanerd-drew/agent-workspace/main/init.sh | bash
#        bash init.sh [--dir .] [--name "Agent"] [--install] [--yes]

set -euo pipefail

DIR="${DIR:-.}"
NAME="${NAME:-}"
YES="${YES:-}"
INSTALL="${INSTALL:-}"

while [ $# -gt 0 ]; do
  case "$1" in
    --dir) DIR="$2"; shift 2 ;;
    --name) NAME="$2"; shift 2 ;;
    --install) INSTALL=1; shift ;;
    --yes|-y) YES=1; shift ;;
    *) echo "Unknown: $1"; exit 1 ;;
  esac
done

cd "$DIR"
DIR=$(pwd)
NAME=${NAME:-$(basename "$DIR")}

echo "  Initializing .agent/ workspace for $DIR"

# --- Detect framework ---
FRAMEWORK="generic"
if [ -f opencode.jsonc ] || [ -d .opencode ]; then FRAMEWORK="opencode"; fi
if [ -f CLAUDE.md ] || [ -d .claude ]; then FRAMEWORK="claude-code"; fi
if [ -f .cursorrules ] || [ -d .cursor ]; then FRAMEWORK="cursor"; fi
echo "  Detected framework: $FRAMEWORK"

# --- Create directories ---
mkdir -p .agent/workflow .agent/memory

# --- Write identity.md ---
cat > .agent/identity.md << 'IDENTITY'
## Identity

- **Name**: {{NAME}}
- **Role**: software engineering agent
- **Voice**: Answer-first, concise, honest
- **Values**: YAGNI, minimal diffs, provenance, verify, filesystem is truth

## Core Directives

1. Read before write — never modify files without reading first
2. QA gate — never declare completion without verification
3. Taste over volume — high-leverage work over busywork

## Behavioral Constraints

- Never expose secrets or API keys
- Never execute destructive operations without confirmation
- Never accept subagent output without verification
IDENTITY
sed -i '' "s/{{NAME}}/$NAME/g" .agent/identity.md
echo "  ✓ .agent/identity.md"

# --- Write rules.md ---
cat > .agent/rules.md << 'RULES'
## Must (Always Do)

1. Read files before modifying them.
2. Verify all changes: lint -> typecheck -> test.
3. Save every non-trivial decision with `remember()`.
4. Ask when uncertain — never guess and proceed.

## Must Not (Never Do)

1. rm -rf /, rm -rf ~, or destructive bulk operations without confirmation.
2. Hardcode secrets, API keys, or tokens in source code.
3. Force-push or rewrite git history.
4. Add dependencies without explaining why.

## Decision Framework

1. Why now? 2. Why this way? 3. What could break? 4. How will we know?
RULES
echo "  ✓ .agent/rules.md"

# --- Write workflow/init.md ---
cat > .agent/workflow/init.md << 'INIT'
## Session Start

1. `recall("recent context")` — restore last session context
2. Save session start: `remember(type="fact", "Session started: {date}")`
3. Check `recall("active decisions")` for in-progress work
INIT
echo "  ✓ .agent/workflow/init.md"

# --- Write workflow/general.md ---
cat > .agent/workflow/general.md << 'GENERAL'
## Standard Sequence

1. **Understand** — 모호하면 질문.
2. **Plan** — 복잡하면 write plan.
3. **Execute** — minimal diff.
4. **Verify** — lint -> typecheck -> test.
5. **Save** — decisions/patterns to `remember()`.

## When Stuck

- `recall("similar problem")` — past similar cases
- If none, ask user
GENERAL
echo "  ✓ .agent/workflow/general.md"

# --- Write AGENTS.md ---
if [ -f AGENTS.md ]; then
  if ! grep -q ".agent/identity.md" AGENTS.md 2>/dev/null; then
    cat > .agents.md.header << 'HEADER'
<!-- Generated by agent-workspace init.sh -->

## Identity

Your identity is defined in `.agent/identity.md`.
Your rules are defined in `.agent/rules.md`.
Workflows are in `.agent/workflow/`.

HEADER
    cat .agents.md.header AGENTS.md > AGENTS.md.tmp && mv AGENTS.md.tmp AGENTS.md
    rm -f .agents.md.header
    echo "  ✓ AGENTS.md updated"
  else
    echo "  ✓ AGENTS.md already references .agent/"
  fi
else
  cat > AGENTS.md << 'AGENTSM'
<!-- Generated by agent-workspace init.sh -->

## Identity

Your identity is defined in `.agent/identity.md`.
Your rules are defined in `.agent/rules.md`.
Workflows are in `.agent/workflow/`.
AGENTSM
  echo "  ✓ AGENTS.md created"
fi

# --- Install memory MCP server if --install ---
if [ -n "$INSTALL" ]; then
  if ! command -v node &>/dev/null; then
    echo "  ⚠  Node.js not found. Install from https://nodejs.org/"
    INSTALL=""
  fi

  AW_HOME="${AGENT_WORKSPACE_HOME:-$HOME/.agent-workspace}"
  if [ ! -d "$AW_HOME" ]; then
    echo "  Downloading agent-workspace (memory MCP server)..."
    git clone --depth 1 https://github.com/humanerd-drew/agent-workspace.git "$AW_HOME" 2>/dev/null || {
      echo "  ⚠  git clone failed. Check network."
      INSTALL=""
    }
  fi

  if [ -n "$INSTALL" ]; then
    echo "  Building memory MCP server..."
    cd "$AW_HOME/packages/memory"
    npm install --silent 2>/dev/null
    npx tsc 2>/dev/null || true
    cd "$DIR"

    MEMORY_NODE="node $AW_HOME/packages/memory/dist/index.js"
    MCP_CMD="node"
    MCP_ARGS="$AW_HOME/packages/memory/dist/index.js --db .agent/memory/knowledge.db"
    echo "  ✓ memory MCP server ready at $AW_HOME"
  fi
fi

# --- Configure MCP server ---
if [ -z "${MCP_CMD:-}" ]; then
  MCP_CMD="npx"
  MCP_ARGS="--yes @agent-workspace/memory --db .agent/memory/knowledge.db"
fi

# Build MCP args as JSON string array
json_args() {
  local out=""
  for a in "$@"; do
    [ -n "$out" ] && out="$out, "
    out="$out\"$a\""
  done
  echo "$out"
}

if [ -z "${MCP_CMD:-}" ]; then
  MCP_CMD="npx"
  MCP_ARGS="-y @agent-workspace/memory --db .agent/memory/knowledge.db"
fi
IFS=' ' read -r -a MCP_ARG_ARRAY <<< "$MCP_ARGS"
MCP_ARGS_JSON=$(json_args "${MCP_ARG_ARRAY[@]}")

case "$FRAMEWORK" in
  opencode)
    if [ -f opencode.jsonc ]; then
      if grep -q "agent-memory" opencode.jsonc 2>/dev/null; then
        echo "  ✓ opencode.jsonc: agent-memory already configured"
      elif grep -q '"mcp"' opencode.jsonc 2>/dev/null; then
        echo "  ⚠  Add to opencode.jsonc \"mcp\" section manually:"
        echo '     "agent-memory": { "type": "local", "command": ["'"$MCP_CMD"'", '"$MCP_ARGS_JSON"'] }'
      else
        python3 -c "
import json, sys
CMD = '''$MCP_CMD'''
ARGS_STR = '''$MCP_ARGS_JSON'''
args = json.loads('[' + ARGS_STR + ']')
with open('opencode.jsonc') as f:
    raw = f.read()
data = json.loads(raw)
if 'mcp' not in data:
    data['mcp'] = {}
data['mcp']['agent-memory'] = {'type': 'local', 'command': [CMD] + args}
with open('opencode.jsonc', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
    f.write(chr(10))
" 2>/dev/null || echo "  \u26a0  Manual: add agent-memory to opencode.jsonc mcp section"
        echo "  ✓ opencode.jsonc: agent-memory MCP added"
      fi
    fi
    ;;
  claude-code)
    mkdir -p .claude
    cat > .claude/settings.local.json << CLAUDEJSON
{
  "mcpServers": {
    "agent-memory": {
      "command": "$MCP_CMD",
      "args": [$MCP_ARGS_JSON]
    }
  }
}
CLAUDEJSON
    echo "  ✓ .claude/settings.local.json: agent-memory added"
    ;;
  cursor)
    mkdir -p .cursor
    cat > .cursor/mcp.json << CURSORJSON
{
  "mcpServers": {
    "agent-memory": {
      "command": "$MCP_CMD",
      "args": [$MCP_ARGS_JSON]
    }
  }
}
CURSORJSON
    echo "  ✓ .cursor/mcp.json: agent-memory added"
    ;;
  generic)
    echo "  ⚠  Manual MCP setup required."
    echo "     Add to your agent's config:"
    echo '     { "type": "local", "command": ["'"$MCP_CMD"'", '"$MCP_ARGS_JSON"'] }'
    ;;
esac

# --- .gitignore ---
if [ -f .gitignore ]; then
  if ! grep -q ".agent/memory/knowledge.db" .gitignore 2>/dev/null; then
    echo ".agent/memory/knowledge.db" >> .gitignore
  fi
fi

echo ""
echo "  ┌─────────────────────────────────────┐"
echo "  │  .agent/ workspace initialized!     │"
echo "  └─────────────────────────────────────┘"
echo ""
echo "  Next steps:"
echo "  1. Review .agent/identity.md and .agent/rules.md"
echo "  2. Start your agent"
